In [1]:
import numpy as np
from sklearn.metrics import ndcg_score
# we have groud-truth relevance of some answers to a query:
true_relevance = np.asarray([[10, 0, 0, 1, 5]])

In [2]:
true_relevance

array([[10,  0,  0,  1,  5]])

In [3]:
scores = np.asarray([[.1, .2, .3, 4, 70]])
ndcg_score(true_relevance, scores)

0.6956940443813076

In [4]:
scores

array([[ 0.1,  0.2,  0.3,  4. , 70. ]])

In [5]:
scores = np.asarray([[.05, 1.1, 1., .5, .0]])
ndcg_score(true_relevance, scores)

0.493680191377376

In [6]:
scores

array([[0.05, 1.1 , 1.  , 0.5 , 0.  ]])